### ISSUE TITLE
Unstable tests

### ISSUE THREAD

**Issue by sslavic** [twitter/distributedlog#14]
```
testReloadConfiguration(com.twitter.distributedlog.config.TestConfigurationSubscription): expected:<1> but was:<null>
```
```
<failure message="expected:&lt;1&gt; but was:&lt;null&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;1&gt; but was:&lt;null&gt;
	at org.junit.Assert.fail(Assert.java:91)
	at org.junit.Assert.failNotEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:126)
	at org.junit.Assert.assertEquals(Assert.java:145)
	at com.twitter.distributedlog.config.TestConfigurationSubscription.testReloadConfiguration(TestConfigurationSubscription.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
```

**Comment by sijie** [comment]
@sslavic does this constantly fail for you?

**Comment by sslavic** [comment]
Now that you asked, I checked couple of times and it seems that it's a general instability of multiple tests e.g.:
```
testNonBlockingRead(com.twitter.distributedlog.TestNonBlockingReads): test timed out after 60000 milliseconds
testBasicWrite(com.twitter.distributedlog.service.TestDistributedLogServer): expected:<3> but was:<1>
```
were failing too, and typically just one fails.

**Comment by sslavic** [comment]
Consider maybe documenting in a wiki page, how to build project, and there specify any recommendation on build tool configuration if it might help having more stable builds.

**Comment by mgodave** [comment]
Looking at the test there is clearly a race condition on the timeout of 100 milliseconds.

**Comment by sijie** [comment]
@sslavic that's a very good suggestion. will add a page to 'how to build'.
